package chess.model

import Colours.{Black, White}

object DefectFixture {

  // TODO: Use TestUtils instead of duplicating implicit functions
  implicit def string2MovePiece(s: String): MovePiece = new MovePiece(s)
  implicit def string2Position(s: String): Position = new Position(s)

  var defect5Moves: List[Move] = List[Move]()
  defect5Moves ::= new MovePiece("g2g4")
  defect5Moves ::= new MovePiece("f7f5")
  defect5Moves ::= new MovePiece("f2f3")
  defect5Moves ::= new MovePiece("b8c6")
  defect5Moves ::= new MovePiece("c2c3")
  defect5Moves ::= new MovePiece("d7d6")
  defect5Moves ::= new MovePiece("a2a3")
  defect5Moves ::= new MovePiece("g7g5")
  defect5Moves ::= new MovePiece("a3a4")
  defect5Moves ::= new MovePiece("f5f4")
  defect5Moves ::= new MovePiece("h2h4")
  defect5Moves ::= new MovePiece("c6b8")
  defect5Moves ::= new MovePiece("e2e4")
  defect5Moves ::= new MovePiece("b8a6")
  defect5Moves ::= new MovePiece("f1b5")
  defect5Moves ::= new MovePiece("c7c6")
  defect5Moves ::= MovePieceCapturing("b5", "c6")
  defect5Moves ::= new MovePiece("c8d7")
  defect5Moves ::= MovePieceCapturing("c6", "d7")
  defect5Moves ::= new MovePiece("e8f7")
  defect5Moves ::= new MovePiece("d7e6")
  defect5Moves ::= new MovePiece("f7e8")
  defect5Moves ::= new MovePiece("e6f7")
  defect5Moves ::= new MovePiece("e8d7")
  defect5Moves ::= new MovePiece("f7e8")
  defect5Moves ::= new MovePiece("d7c8")
  defect5Moves ::= new MovePiece("e8d7")
  defect5Moves ::= new MovePiece("c8b8")
  defect5Moves ::= new MovePiece("d7c8")
  defect5Moves ::= new MovePiece("b8c7")
  defect5Moves ::= MovePieceCapturing("c8", "b7")
  defect5Moves ::= MovePieceCapturing("g5", "h4")
  defect5Moves ::= new MovePiece("b2b3")
  defect5Moves ::= new MovePiece("d8b8")
  defect5Moves ::= new MovePiece("b7d5")
  defect5Moves ::= new MovePiece("b8e8")
  defect5Moves ::= MovePieceCapturing("d5", "g8")
  defect5Moves ::= new MovePiece("h7h6")
  defect5Moves ::= new MovePiece("c3c4")
  defect5Moves ::= new MovePiece("c7b6")
  defect5Moves ::= new MovePiece("c4c5")
  defect5Moves ::= MovePieceCapturing("d6", "c5")
  defect5Moves ::= new MovePiece("a4a5")
  defect5Moves = defect5Moves.reverse

  /* This move should be rejected after playing the defect5Moves moves */
  val defect5FinalMove: Castle = Castle(Black, Long)

  var defect6Moves: List[Move] = List[Move]()
  defect6Moves ::= new MovePiece("d2d4")
  defect6Moves ::= new MovePiece("d7d6")
  defect6Moves ::= new MovePiece("d1d2")
  defect6Moves ::= new MovePiece("e7e6")
  defect6Moves ::= new MovePiece("g1h3")
  defect6Moves ::= new MovePiece("f7f5")
  defect6Moves ::= new MovePiece("h3g5")
  defect6Moves ::= MovePieceCapturing("g7", "g5")
  defect6Moves ::= new MovePiece("b2b4")
  defect6Moves ::= new MovePiece("b7b5")
  defect6Moves ::= new MovePiece("a2a4")
  defect6Moves ::= MovePieceCapturing("b5", "a4")
  defect6Moves ::= new MovePiece("b1c3")
  defect6Moves ::= new MovePiece("g8h6")
  defect6Moves ::= new MovePiece("f2f4")
  defect6Moves ::= MovePieceCapturing("g5", "f4")
  defect6Moves ::= new MovePiece("g2g4")
  defect6Moves ::= EnPassant("f4", "g3")
  defect6Moves ::= new MovePiece("a1b1")
  defect6Moves ::= MovePieceCapturing("g3", "h2")
  defect6Moves ::= new MovePiece("c3d1")
  defect6Moves ::= new MovePiece("d6d5")
  defect6Moves ::= new MovePiece("e2e3")
  defect6Moves ::= MovePieceCapturing("f8", "b4")
  defect6Moves ::= new MovePiece("f1b5")
  defect6Moves ::= new MovePiece("c8d7")
  defect6Moves ::= MovePieceCapturing("b5", "d7")
  defect6Moves ::= MovePieceCapturing("d8", "d7")
  defect6Moves = defect6Moves.reverse

  /* This move should be rejected after playing the defect6Moves moves */
  val defect6FinalMove: Castle = Castle(White, Short)


}